process_queue:
  address: localhost
  port: 5672
  credentials:
    username: mm-test
    password: mm-test
  ssh:
    username: mm
    path_to_privkey: /home/mm/.ssh/cloud.key
  skip_deployment: false
database:
  address: localhost
  port: 27018
  credentials:
    username: admin
    password: admin
  ssh:
    username: mm
    path_to_privkey: /home/mm/.ssh/cloud.key
  skip_deployment: false
hosts:
  - address: localhost
    username: mm
    path_to_privkey: /home/mm/.ssh/cloud.key
    servers:
      - name: ocrd-cis-ocropy-binarize
        deploy_type: native
        port: 9091
      - name: ocrd-anybaseocr-crop
        deploy_type: native
        port: 9092
      - name: ocrd-cis-ocropy-denoise
        deploy_type: native
        port: 9093
      - name: ocrd-cis-ocropy-deskew
        deploy_type: native
        port: 9094
      - name: ocrd-tesserocr-segment-region
        deploy_type: native
        port: 9095
      - name: ocrd-segment-repair
        deploy_type: native
        port: 9096
      - name: ocrd-cis-ocropy-clip
        deploy_type: native
        port: 9097
      - name: ocrd-cis-ocropy-segment
        deploy_type: native
        port: 9098
      - name: ocrd-cis-ocropy-dewarp
        deploy_type: native
        port: 9099
      - name: ocrd-tesserocr-recognize
        deploy_type: native
        port: 9100

